
# Results

```{r, include = F, cache = F}
library(kableExtra)
source("report-functions.R")
```

## Identification of ICU capacity limits by French Region

```{r, cache = F, fig.cap = "Predicted needs of ICU beds in the 13 French Regions. The red line stands for the ICU capacity limit, the dotted line stands for the scenario with $R_0 = 2.25$, the black lines for the worst and best case scenarios ($R_0 = 3$ and $R_0 = 1.5$ respectively).", dev = "png"}
## Run model
outcomes = run_model(R0 = 3)

## within a week
data1w = outcomes[Time < as.Date("2020-03-21"), ]
## within two weeks
data2w = outcomes[Time < as.Date("2020-03-28"), ]
## At 1 month
data1 = outcomes[Time < as.Date("2020-04-08"), ]
## From month 1 to 2
data2 = outcomes[Time >= as.Date("2020-04-08") & Time < as.Date("2020-05-07"), ]
## Both months
data1and2 = outcomes[Time < as.Date("2020-05-07"), ]

outcomesR1.5 = run_model(R0 = 1.5)
outcomesR2.25 = run_model(R0 = 2.25)

t_range = seq(as.Date("2020-03-14"), as.Date("2020-04-14"), by = "day")
data1mR1.5 = outcomesR1.5[Time %in% t_range, 
                          .(AllAgeBedICU = sum(BedICU)), by = c("Time", "Region")]
data1mR2.25 = outcomesR2.25[Time %in% t_range,
                            .(AllAgeBedICU = sum(BedICU)), by = c("Time", "Region")]
data1mR3.0 = outcomes[Time %in% t_range, 
                      .(AllAgeBedICU = sum(BedICU)), by = c("Time", "Region")]

ThresholdCapacityDateR1.5 = merge(data1mR1.5, ReaCapacity, by = "Region")[AllAgeBedICU>Capacity, .SD[1, Time], by = "Region"]

ThresholdCapacityDateR2.25 = merge(data1mR2.25, ReaCapacity, by = "Region")[AllAgeBedICU>Capacity, .SD[1, Time], by = "Region"]

ThresholdCapacityDateR3 = merge(data1mR3.0, ReaCapacity, by = "Region")[AllAgeBedICU>Capacity, .SD[1, Time], by = "Region"]

setorder(ThresholdCapacityDateR3, V1)
neworder = as.character(ThresholdCapacityDateR3$Region)
data1mR1.5[, Region := factor(Region, levels = neworder)]
# data1mR2.25[, Region := factor(Region, levels = neworder)]
# data1mR3.0[, Region := factor(Region, levels = neworder)]
reaMetCap = ReaCapacity[!Region %in% c("France", "Metropole")]
#reaMetCap[, Region := factor(Region, levels = neworder)]

p = ggplot() +
    geom_line(data = data1mR1.5, aes(x = Time, y = AllAgeBedICU)) +
    geom_line(data = data1mR2.25, aes(x = Time, y = AllAgeBedICU), linetype = "dotted") +
    geom_line(data = data1mR3.0, aes(x = Time, y = AllAgeBedICU)) +
    geom_hline(data = reaMetCap, aes(yintercept = Capacity), color = "red") +
    facet_wrap(~Region, nrow = 5 ) + 
    scale_x_date(name = NULL) +
    scale_y_continuous(name = "ICU beds", trans = "log10", limits = c(1,1300)) +
    theme_classic() + 
    theme(axis.text.x = element_text(angle = 40, hjust = 1)) #+
    #ggtitle("Predicted needs of ICU beds by French Region (R0: 1.5, 2.25, 3)")
p

```

```{r, echo = FALSE}
options(knitr.kable.NA = '')
caption = "Estimated date of ICU capacity overrun in the 13 metropolitan French Regions, for $R_0$ 1.5, 2.25, and 3."
mergedData = merge(ThresholdCapacityDateR1.5,ThresholdCapacityDateR2.25, 
                   by = "Region", all = TRUE)
mergedData = merge(mergedData, ThresholdCapacityDateR3,
                   by = "Region", all = TRUE)
setorderv(mergedData, cols = c("V1.x", "V1.y", "V1"), order = c(1,1,1), na.last = TRUE)
setnames(mergedData, old = 2:4, new = c("$R_0$ 1.5", "$R_0$ 2.25", "$R_0$ 3"))

knitr::kable(mergedData,
             escape = FALSE,
             digits = 0,
             caption = caption,
             format = "latex")

```

## Predicted outcomes by region

```{r}
data = outcomesR1.5[Time < as.Date("2020-04-14"), ]
outcomes1 = get_outcomes_byreg(data = data)

data = outcomesR2.25[Time < as.Date("2020-04-14"), ]
outcomes2 = get_outcomes_byreg(data = data)

data = outcomes[Time < as.Date("2020-04-14"), ]
outcomes3 = get_outcomes_byreg(data = data)

```

```{r}
DTgen = merge(outcomes1, outcomes2, by = "Region")
DTgen = merge(DTgen, outcomes3, by = "Region")

DT = DTgen[, c(1,2,7,12,3,8,13,6,11,16)]

colnames(DT)[c(2,5,8)] = "$R_0$ 1.5"
colnames(DT)[c(3,6,9)] = "$R_0$ 2.25"
colnames(DT)[c(4,7,10)] = "$R_0$ 3"

caption = "Predicted number of infected cases, severe cases, and deaths, from March 10 to April 7, 2020, by Region, for $R_0$ values of 1.5, 2.25, and 3."

kableExtra::landscape(knitr::kable(DT,
             escape = FALSE,
             digits = 0,
             caption = caption,
             format = "latex") %>%
    kableExtra::add_header_above(header = c(" " = 1,
                                            "Infected" = 3,
                                            "Severe cases" = 3,
                                            "Deaths" = 3)) )
#%>%
#    kableExtra::scroll_box(width = "100%")

```

```{r}

DThosp = DTgen[, c(1,4,9,14,5,10,15)]

colnames(DThosp)[c(2,5)] = "$R_0$ 1.5"
colnames(DThosp)[c(3,6)] = "$R_0$ 2.25"
colnames(DThosp)[c(4,7)] = "$R_0$ 3"
caption = "Predicted cumulated number of cases admitted into intensive care units, cases requiring ventilation, from 10 March 2020 to 07 April 2020, by region, for $R_0$ values of 1.5, 2.25, and 3."
knitr::kable(DThosp,
             escape = FALSE,
             digits = 0,
             caption = caption,
             format = "latex") %>%
    kableExtra::add_header_above(header = c(" " = 1,
                                            "ICU" = 3,
                                            "Ventilation" = 3))
```
