# Discussion
In the context of a lack of modeling data on COVID-19 epidemic in France, the purpose of our study was to provide at one month quantitative data on the spread of the virus in French Regions and on hospitals' requirements, especially regarding ICU beds and ventilation needs.

Until April 14, we predict a rise in the total number of infected cases in all metropolitan French Regions. At the national level, the total number of infected cases is expected to range from 22,872 in the best case ($R_0=1.5$) to 161,832 in the worst considered case ($R_0=3$). Regarding the total number of deaths, it is expected to vary from 1,021 to 11,032, respectively. At the regional level, all ICU capacities may be overrrun in the worst scenario, Centre-Val de Loire being the last region to reach its limits on April 12. Only seven Regions may lack ICU beds in the mid scenario ($R_0=2.25$) and only one in the best case. In the three scenarii, Corse may be the first Region to see its ICU capacities overrrun with a delay of one week between each scenario, which may be due to its low ICU capacity (18 beds). The two other Regions, whose capacity will be overrun closely, are Grand-Est and Bourgogne-France-Comté, despite their high number of ICU beds (465 and 198, respectively).

COVID-19 mortality risk is not only dependent on the intrinsic virus' characteristics, but depends also on health care capacities, especially ICU. Italy is already seeing its ICU capacities exceeded, as well as several hospitals in France. However, few studies have tried to forecast ICU needs. Grasselli and colleagues used linear and exponential models to estimate ICU demand in Lombardy, Italy, from March 7 to March 20 [@Grasselli]. They concluded that the health care system could not sustain an uncontrolled outbreak, and that strong containment measures were needed. Remuzzi and Remuzzi fitted exponential models and predicted that the Italian health care system could be at maximum capacity by March 14 [@Remuzzi]. Here, we found that ICU capacities would be rapidly exceeded in several Regions in France, even in optimistic scenarios. Incapacity to provide adequate treatment to critically ill patients could further increase the already substantial death toll of the epidemic.

Besides limits inherent to each transmission model, this work has several specific limitations. We are only presenting forecasts at one month, as long term predictions may be unreliable due to the few data available to calibrate the model concerning the epidemic in France. The critical factor that remains unknown to this date is the potential impact of seasonality on the transmission dynamic of COVID-19. Danon and colleagues modeled seasonal transmission by introducing a time-varying transmission rate. [@danon-medrxiv] They estimated that a 50% reduction in transmission during summer months would result in a smaller epidemic before the summer, followed by a resurgence in cases in the following winter. However, whether SARS-CoV-2 transmission will be affected by seasonal variations remains unclear. Although many infectious diseases have seasonal patterns, like influenza or other coronaviruses, newly introduced viruses can behave differently. Several experts suggest that the impact of seasonality on COVID-19 transmission might be very modest, [@Lipsitch;@Cohen] therefore we did not included such a seasonality in our model at the time. 

Regarding the prediction of ICU needs, the ICU capacities used in this study are theoretical and based on annual data, [@DREES] and may not reflect exactly current ICU capacities. However, the potential discrepancies are likely to be modest and should not impact the interpretation of the results. Also, we assumed a fixed length of stay of 15 days in ICU as observed in foreign countries. This value could vary across patients and locations, and could slightly bias the estimation of ICU needs in our study. To overcome this bias, we plan to use hospitalization data provided by regional health agencies (ARS), which may help to have better predictions of beds use.

We restricted our model to metropolitan France, as overseas Regions are at a lower epidemic stage at the moment, and the transmission dynamics are likely to differ from metropolitan France. Finally, it must be noted that spatial division of the French territory used in this model does not exactly reflect administrative boundaries of the French Regions, as it was based on the merge of each Voronoi polygons representing referral centers' catchment areas. However, division by catchment areas might help to better estimate the pressure on the referral centers, as people are more likely to be referred to hospitals based on geographical distance rather than administrative boundaries.

To mitigate the epidemic, the French government announced a series of nation-wide measures, of increasing importance. On February 29, gatherings were restricted to 5,000 persons in confined settings. This threshold has since been revised downwards, with 5,000 persons on March 8, and 100 persons on March 13. On March 12, schools and universities were asked to close starting from March 16, and voluntary household quarantine and social distancing of those over 70 years of age were recommended. Finally, on March 14, the stage 3 of the epidemic was declared. In consequence, all non-essential public places (non-food shops, restaurants, bars for example) are closed, and people are enjoined to stay home as much as possible, limit social interactions, and limit travels. These different mitigation measures were not directly implemented in the present study, but their impact was assessed indirectly by modifying the value of the reproduction number. In order to take them into account, we plan to modify the contact matrix used in the model according to the type of contact (home, work, school or others).


# Conclusion

While preliminary, our analysis shows that, even in the best case scenario, the French healthcare system will very soon be overwhelmed. While drastic social distancing measures may temper our results, a massive reorganization leading to an expansion of French ICU capacities seems to be necessary to manage the coming wave of critically affected COVID-19 patients.
