---
title: "COVID-19: Forecasting short term hospital needs in France"
author: Clément Massonnaud^1^^,2^\footnote{Both authors contributed equally.}, Jonathan Roux^1^$^\ast$, Pascal Crépey^1^\footnote{corresponding author - pascal.crepey@ehesp.fr}
include-before: ^1^ UPRES-EA 7449 REPERES « Recherche en Pharmaco-Epidémiologie et Recours aux Soins » – EHESP – Université de Rennes, 15 avenue du Professeur-Léon-Bernard, CS 74312, 35043 Rennes, France. ^2^ Rouen University Hospital, Department of Biostatistics, F 76031 Rouen, France.
date: "`r Sys.Date()`"
knit: "bookdown::render_book"
csl: "../doc/biblio/the-lancet.csl"
documentclass: article
#documentclass: krantz
link-citations: yes
colorlinks: yes
always_allow_html: true
site: bookdown::bookdown_site
fontsize: 11pt
geometry: margin=0.8in
rmd_files: ["index.rmd", "01-intro-method.rmd", "02-results.rmd", "03-discussion.rmd", "09-references.rmd"]
output:
  bookdown::pdf_book:
    toc: false
bibliography: ../doc/biblio/references.bib
#output: rticles::plos_article
#csl: plos.csl
---


```{r echo = F}
knitr::opts_chunk$set(echo = F, cache = T, message = F, warnings = F)
```
```{r cache = F, echo=FALSE, message=FALSE}
# Document and load package (no need to build or install)
#devtools::document()
library(HospiCov)
library(ggplot2)
```


