// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// engine_run
arma::mat engine_run(List params, arma::mat init);
RcppExport SEXP _shinyCov_engine_run(SEXP paramsSEXP, SEXP initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type init(initSEXP);
    rcpp_result_gen = Rcpp::wrap(engine_run(params, init));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_shinyCov_engine_run", (DL_FUNC) &_shinyCov_engine_run, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_shinyCov(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
