# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

engine_run <- function(params, init) {
    .Call('_shinyCov_engine_run', PACKAGE = 'shinyCov', params, init)
}

