# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function that initialize (or reinitialize) the initial state of the model
#' @param params list of various model parameters
#' @param init initial state of the model
#'
#' @return a matrix of the result
#' @export
engine_run <- function(params, init) {
    .Call(`_HospiCov_engine_run`, params, init)
}

